# SwiftLint configuration for AccessyApp

# Paths to include/exclude
included:
  - AccessyApp

excluded:
  - AccessyApp/Assets.xcassets
  - .build
  - DerivedData
  - build

# Rules to enable
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - non_optional_string_data_conversion
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo # Allow TODO comments
  - type_body_length # Allow larger types
  - function_body_length # Allow longer functions for crypto code
  - trailing_closure # SwiftUI style preference
  - multiple_closures_with_trailing_closure # SwiftUI alert/sheet style

# Custom rule configurations
type_name:
  min_length: 2
  max_length: 50

identifier_name:
  min_length: 3
  max_length: 50
  excluded:
    - id
    - iv

line_length:
  warning: 120
  error: 160
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_parameter_count:
  warning: 8
  error: 10

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

# Force unwrapping is sometimes necessary in crypto code
force_unwrapping:
  severity: warning

# Force cast should be explicitly disabled with comment when necessary
force_cast:
  severity: error

# Non-optional string to data conversion - allow for simple literals
non_optional_string_data_conversion:
  severity: warning

# Reporter type
reporter: "xcode"
